/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/tutorial/{id}': {
    get: operations['getById'];
    put: operations['update'];
  };
  '/purchasable/{id}': {
    get: operations['getById_1'];
    put: operations['update_1'];
    delete: operations['delete'];
  };
  '/profile': {
    get: operations['getCurrentUser'];
    put: operations['updateCurrentUser'];
    patch: operations['patchCurrentUser'];
  };
  '/game/{id}': {
    get: operations['getById_4'];
    put: operations['update_2'];
    delete: operations['deleteGame'];
  };
  '/game/{id}/api-key': {
    put: operations['createApiKey'];
    delete: operations['revokeApiKey'];
  };
  '/tutorial': {
    get: operations['getByGameId'];
    post: operations['create'];
  };
  '/purchasable': {
    get: operations['search'];
    post: operations['create_1'];
  };
  '/matchmaking/search': {
    post: operations['searchMatch'];
  };
  '/matchmaking/cancel': {
    post: operations['cancelSearch'];
  };
  '/match/{matchId}/replay/{playerToken}': {
    post: operations['saveReplay'];
  };
  '/match/{id}/score': {
    post: operations['updateScore'];
  };
  '/match/{id}/abort': {
    post: operations['abortPlayer'];
  };
  '/match/join': {
    post: operations['joinMatch'];
  };
  '/game': {
    get: operations['search_2'];
    post: operations['create_2'];
  };
  '/checkout/fast': {
    post: operations['fastCheckout'];
  };
  '/basket/items': {
    post: operations['addItemToBasket'];
    patch: operations['updateItemInBasket'];
  };
  '/auth/register': {
    post: operations['register'];
  };
  '/auth/refresh': {
    post: operations['refresh'];
  };
  '/auth/login': {
    post: operations['login'];
  };
  '/auth/change-username': {
    post: operations['changeUsername'];
  };
  '/auth/change-password': {
    post: operations['changePassword'];
  };
  '/auth/change-email': {
    post: operations['changeEmail'];
  };
  '/wallet': {
    get: operations['getUserWallet'];
  };
  '/stats/user/{userId}/aggregate/winRatio': {
    get: operations['getAggregatedUserWinRatio'];
  };
  '/profile/{id}': {
    get: operations['getById_2'];
  };
  '/notification': {
    get: operations['search_1'];
  };
  '/matchmaking/ticket/{id}': {
    get: operations['getTicketStatus'];
  };
  '/match/{matchId}/replay/{userId}': {
    get: operations['findReplay'];
  };
  '/match/{id}': {
    get: operations['getById_3'];
    delete: operations['deleteById'];
  };
  '/match/{id}/player/{playerToken}': {
    get: operations['getPlayerInfo'];
  };
  '/match/playerToken/{playerToken}': {
    get: operations['getByPlayerToken'];
  };
  '/match/history': {
    get: operations['searchHistory'];
  };
  '/match/history/{id}': {
    get: operations['getHistoryById'];
  };
  '/match/history/user/{userId}': {
    get: operations['getHistoryForUser'];
  };
  '/game/info': {
    get: operations['getGameInfo'];
  };
  '/basket': {
    get: operations['getCurrentBasket'];
    delete: operations['deleteCurrentBasket'];
  };
  '/basket/items/{itemId}': {
    delete: operations['deleteItemInBasket'];
  };
}

export interface components {
  schemas: {
    /**
     * @description System-wide error response object
     * @example [object Object]
     */
    ErrorResponse: {
      /** @description Error status name */
      status: string;
      /**
       * Format: int32
       * @description Internal status code
       */
      statusCode: number;
      /** @description Error reason */
      error?: { [key: string]: unknown } | null;
    };
    /** @description UpdateTutorial holds the required information to update a TutorialProgress */
    UpdateTutorialRequest: {
      /** @description State of the tutorial */
      finished: boolean;
    };
    /** @description TutorialProgress contains the current state of a given game tutorial for a player */
    TutorialProgressResponse: {
      /** @description Tutorial id */
      id: string;
      /** @description Tutorial user */
      userId: string;
      /** @description Tutorial game */
      gameId: string;
      /** @description Tutorial game */
      finished: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdatePurchasableRequest: {
      title: string;
      description: string;
      iconUrl: string;
      bannerUrl: string;
      type: string;
      /** Format: int32 */
      price?: number;
      /** Format: int32 */
      amount: number;
      properties: { [key: string]: string };
      tags: string[];
      /** Format: int32 */
      bonus?: number;
      /** Format: int32 */
      oldPrice?: number;
    };
    PurchasableResponse: {
      id: string;
      title: string;
      description: string;
      iconUrl: string;
      bannerUrl: string;
      type: string;
      /** Format: int32 */
      oldPrice?: number;
      /** Format: int32 */
      price: number;
      /** Format: int32 */
      bonus?: number;
      /** Format: int32 */
      amount: number;
      tags: string[];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    UpdateProfileRequest: {
      avatarUrl: string;
    };
    ProfileResponse: {
      id: string;
      username: string;
      avatarUrl: string;
    };
    UpdateGameRequest: {
      title: string;
      subtitle: string;
      iconUrl: string;
      bannerUrl: string;
      description: string;
      tutorialVideoUrl: string;
      genre: string;
      matchTiers: string[];
      gameUrl: string;
      tags: string[];
    };
    CurrencyResponse: {
      /** @description Id of currency in wallet */
      identifier: string;
      /**
       * Format: int64
       * @description Amount of given currency in wallet
       */
      amount: number;
    };
    DenominationResponse: {
      identifier: string;
      /** Format: int32 */
      totalPlayerCount: number;
      entryCosts: components['schemas']['CurrencyResponse'][];
      possibleWins: components['schemas']['CurrencyResponse'][];
    };
    /** @description Game holds all belongings of a game. */
    GameResponse: {
      /** @description Game id */
      id: string;
      /** @description Game title */
      title: string;
      /** @description Game subtitle */
      subtitle: string;
      /** @description Game icon url */
      iconUrl: string;
      /** @description Game banner url */
      bannerUrl: string;
      /** @description Game description */
      description: string;
      /** @description Game tutorial video */
      tutorialVideoUrl: string;
      /** @description Game genre */
      genre: string;
      /** @description Game genre */
      gameUrl: string;
      /** @description Playable match tiers */
      matchTiers: components['schemas']['MatchTierResponse'][];
      /** @description Game owner */
      ownerId: string;
      tags: string[];
      /** Format: int32 */
      playersCount: number;
      /** Format: int32 */
      popularity: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @description Playable match tiers */
    MatchTierResponse: {
      /** @enum {string} */
      identifier: '1vs1' | 'tournament';
      playerPool: string;
      realtime: boolean;
      denominations: components['schemas']['DenominationResponse'][];
    };
    ApiKeyResponse: {
      ownerId: string;
      gameId: string;
      value: string;
      revoked: boolean;
    };
    /** @description CreateTutorial holds the required information to create a TutorialProgress */
    CreateTutorialRequest: {
      /** @description GameId of the tutorial */
      gameId: string;
    };
    CreatePurchasableRequest: {
      title: string;
      description: string;
      iconUrl: string;
      bannerUrl: string;
      type: string;
      /** Format: int32 */
      price: number;
      /** Format: int32 */
      amount: number;
      properties: { [key: string]: string };
      tags: string[];
      /** Format: int32 */
      bonus?: number;
      /** Format: int32 */
      oldPrice?: number;
    };
    SearchMatchRequest: {
      gameId: string;
      matchTier: string;
      denominationTier: string;
    };
    PlayerResponse: {
      userId: string;
      username: string;
      avatarUrl: string;
    };
    TicketResponse: {
      id: string;
      playerToken: string;
      ticketIds: string[];
      status: string;
      players: components['schemas']['PlayerResponse'][];
    };
    CancelSearchRequest: {
      ticketId: string;
    };
    /** @description Writes a replay to the storage for a given match and player in that match. Replays can be written only once before a match is finished for a given player. This is indicated by submitted a final score for the player. */
    SaveReplayRequest: {
      /** @description Should be a base64 encoded string for binary data, an escaped json string, or a csv string. This data can be retrieved later in matches for replays that are completed or bot replays that were assigned to a match. The payload can also be metadata containing an ID/URL/Redirect that creates a foreign key relationship for a replay storage that is used by the game. Payloads can not be larger than ~16MB. If that is exceeded, an internal error will occur. */
      payload: string;
    };
    UpdateScoreRequest: {
      /** Format: int32 */
      score: number;
      playerToken: string;
      finalSnapshot: boolean;
    };
    AbortPlayerRequest: {
      playerToken: string;
    };
    AvailableReplayResponse: {
      matchId: string;
      userId: string;
    };
    MatchResponse: {
      id: string;
      /** @enum {string} */
      matchState:
        | 'creating'
        | 'running'
        | 'finished'
        | 'noWinner'
        | 'timedOut'
        | 'deleted';
      participants: components['schemas']['ParticipantResponse'][];
      result: components['schemas']['MatchResultResponse'];
      matchTier: string;
      denomination: components['schemas']['DenominationResponse'];
      possibleWins: components['schemas']['CurrencyResponse'][];
      entryCosts: components['schemas']['CurrencyResponse'][];
      gameId: string;
      /** Format: date-time */
      timeoutAt: string;
      /** Format: date-time */
      deletedAt?: string;
      /** Format: date-time */
      finishedAt?: string;
      scoreSnapshots: components['schemas']['ScoreSnapshotResponse'][];
      availableReplays: components['schemas']['AvailableReplayResponse'][];
      /** @enum {string} */
      matchDifficulty?: 'beginner' | 'medium' | 'hard';
    };
    MatchResultResponse: {
      winners: components['schemas']['ParticipantResultResponse'][];
      losers: components['schemas']['ParticipantResultResponse'][];
    };
    ParticipantResponse: {
      userId: string;
      username: string;
      avatarUrl: string;
      /** @enum {string} */
      playerMatchState: 'joining' | 'playing' | 'aborted' | 'finished';
      /**
       * Format: date-time
       * @description The time when the player joined the match, if player has not joined yet then the value is null.
       */
      joinedAt?: string;
    };
    ParticipantResultResponse: {
      userId: string;
      /** Format: int32 */
      score: number;
      /** Format: int32 */
      earning: number;
    };
    ScoreSnapshotResponse: {
      userId: string;
      /** Format: int32 */
      score?: number;
      /** Format: date-time */
      timestamp: string;
      finalSnapshot: boolean;
    };
    JoinMatchRequest: {
      playerToken: string;
    };
    CreateGameRequest: {
      title: string;
      subtitle: string;
      iconUrl: string;
      bannerUrl: string;
      description: string;
      tutorialVideoUrl: string;
      genre: string;
      matchTiers: string[];
      gameUrl: string;
      tags: string[];
    };
    FastCheckoutRequest: {
      purchasableId: string;
    };
    CheckoutItemResponse: {
      purchasableId: string;
      /** Format: int32 */
      amount: number;
    };
    CheckoutResponse: {
      items: components['schemas']['CheckoutItemResponse'][];
      status: string;
    };
    AddItemRequest: {
      purchasableId: string;
      /** Format: int32 */
      amount: number;
    };
    BasketItemResponse: {
      purchasableId: string;
      /** Format: int32 */
      amount: number;
    };
    BasketResponse: {
      userId: string;
      items: components['schemas']['BasketItemResponse'][];
    };
    /** @description Register request to create a new user through the auth service */
    RegisterRequest: {
      /** @description User's email */
      email: string;
      /** @description Optional username - must be unique. If not set, the username will be generated. */
      username?: string;
      /** @description User's password. Must be a least 6 characters long. */
      password: string;
      /**
       * @description The account type for the user.
       * @enum {string}
       */
      accountType: 'player' | 'developer' | 'staff';
    };
    AuthToken: {
      userId: string;
      accessToken: string;
      /** Format: int64 */
      expiresIn: number;
      /** Format: int64 */
      refreshExpiresIn: number;
      refreshToken: string;
      /** Format: int64 */
      notBeforePolicy: number;
      /**
       * @description A user can have multiple roles. Though normally only one of those is defined to reflect the account type but can also be other roles.
       * @enum {array}
       */
      roles: 'ROLE_PLAYER' | 'ROLE_DEVELOPER' | 'ROLE_STAFF';
      /** @description The account types for the user. Normally only one. This will contain only roles that represent account types without any prefix. */
      accountTypes: ('player' | 'developer' | 'staff')[];
    };
    /** @description TokenExchange request to exchange the token with a new access token */
    RefreshExchangeRequest: {
      /** @description Refresh token will be exchanged with an auth token */
      refreshToken: string;
    };
    /** @description Login request to login through the auth service */
    LoginRequest: {
      /** @description User's email */
      email: string;
      /** @description User's password. Must be a least 6 characters long. */
      password: string;
    };
    ChangeUsernameRequest: {
      userId: string;
      password: string;
      newUsername: string;
    };
    ChangePasswordRequest: {
      userId: string;
      currentPassword: string;
      newPassword: string;
    };
    ChangeEmailRequest: {
      userId: string;
      password: string;
      newEmail: string;
    };
    PatchProfileRequest: {
      avatarUrl?: string;
    };
    UpdateItemRequest: {
      purchasableId: string;
      /** Format: int32 */
      amount: number;
    };
    /** @description Wallet entries */
    WalletEntryResponse: {
      /** @description Id of purchasables in wallet */
      purchasableId: string;
      /**
       * Format: int32
       * @description Amount of given purchasable in wallet
       */
      amount: number;
    };
    /** @description Wallet holds all belongings of a user. It contains purchasables and currencies. */
    WalletResponse: {
      /** @description Wallet owner */
      userId: string;
      /** @description Wallet entries */
      entries: components['schemas']['WalletEntryResponse'][];
      /** @description Wallet currencies */
      currencies: components['schemas']['CurrencyResponse'][];
    };
    Pageable: {
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      sort?: string[];
    };
    PageTutorialProgressResponse: {
      content: components['schemas']['TutorialProgressResponse'][];
      /** Format: int32 */
      totalPages: number;
      /** Format: int64 */
      totalElements: number;
      first: boolean;
      last: boolean;
      /** Format: int32 */
      number: number;
      /** Format: int32 */
      size: number;
      /** Format: int32 */
      numberOfElements: number;
      empty: boolean;
    };
    WinRatioResponse: {
      results: components['schemas']['WinRatioResponseEntry'][];
    };
    WinRatioResponseEntry: {
      /** Format: date-time */
      period: string;
      /** Format: int64 */
      played: number;
      /** Format: int64 */
      won: number;
      /** Format: int64 */
      lost: number;
    };
    PagePurchasableResponse: {
      content: components['schemas']['PurchasableResponse'][];
      /** Format: int32 */
      totalPages: number;
      /** Format: int64 */
      totalElements: number;
      first: boolean;
      last: boolean;
      /** Format: int32 */
      number: number;
      /** Format: int32 */
      size: number;
      /** Format: int32 */
      numberOfElements: number;
      empty: boolean;
    };
    MatchNotificationPayloadResponse: {
      id: string;
      name: string;
      status: string;
      possibleWins: components['schemas']['CurrencyResponse'][];
      participants: components['schemas']['ParticipantResponse'][];
    };
    /** @description Based on the type it contains an object such as MatchNotificationPayload when type is match */
    NotificationPayloadResponse: Partial<
      components['schemas']['MatchNotificationPayloadResponse']
    >;
    /** @description NotificationResponse contains a type and a payload */
    NotificationResponse: {
      /** @enum {string} */
      type: 'match';
      payload: components['schemas']['NotificationPayloadResponse'];
    };
    PageNotificationResponse: {
      content: components['schemas']['NotificationResponse'][];
      /** Format: int32 */
      totalPages: number;
      /** Format: int64 */
      totalElements: number;
      first: boolean;
      last: boolean;
      /** Format: int32 */
      number: number;
      /** Format: int32 */
      size: number;
      /** Format: int32 */
      numberOfElements: number;
      empty: boolean;
    };
    /** @description A finished replay that was found. */
    FindReplayResponse: {
      /** @description The match from which this replay originates. */
      matchId: string;
      participant: components['schemas']['ParticipantResponse'];
      /** @description This is the payload of the replay in the format defined by the game. */
      payload: string;
      /**
       * Format: date-time
       * @description The server time in UTC when the replay was saved.
       */
      createdAt: string;
    };
    MatchHistoryResponse: {
      id: string;
      matchId: string;
      participants: components['schemas']['ParticipantResponse'][];
      result: components['schemas']['MatchResultResponse'];
      matchTier: string;
      denominationTier: string;
      possibleWins: components['schemas']['CurrencyResponse'][];
      entryCosts: components['schemas']['CurrencyResponse'][];
      gameId: string;
      /** Format: date-time */
      timeoutAt: string;
      /** Format: date-time */
      finishedAt: string;
    };
    PageMatchHistoryResponse: {
      content: components['schemas']['MatchHistoryResponse'][];
      /** Format: int32 */
      totalPages: number;
      /** Format: int64 */
      totalElements: number;
      first: boolean;
      last: boolean;
      /** Format: int32 */
      number: number;
      /** Format: int32 */
      size: number;
      /** Format: int32 */
      numberOfElements: number;
      empty: boolean;
    };
    PageGameResponse: {
      content: components['schemas']['GameResponse'][];
      /** Format: int32 */
      totalPages: number;
      /** Format: int64 */
      totalElements: number;
      first: boolean;
      last: boolean;
      /** Format: int32 */
      number: number;
      /** Format: int32 */
      size: number;
      /** Format: int32 */
      numberOfElements: number;
      empty: boolean;
    };
  };
}

export interface operations {
  getById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Tutorial loaded successfully. */
      200: {
        content: {
          'application/json': components['schemas']['TutorialProgressResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  update: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** The tutorial was updated successfully */
      200: {
        content: {
          'application/json': components['schemas']['TutorialProgressResponse'];
        };
      };
      /** Validation failed, e.g. finished is not set */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Tournament could not be found by the given id */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** If a tutorial could not be updated, a CONFLICT will be returned. */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateTutorialRequest'];
      };
    };
  };
  getById_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Purchasable was found */
      200: {
        content: {
          'application/json': components['schemas']['PurchasableResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Purchasable was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  update_1: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['PurchasableResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdatePurchasableRequest'];
      };
    };
  };
  delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Accepted */
      202: unknown;
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getCurrentUser: {
    responses: {
      /** Your current profile profile */
      200: {
        content: {
          'application/json': components['schemas']['ProfileResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  updateCurrentUser: {
    responses: {
      /** The updated profile profile */
      200: {
        content: {
          'application/json': components['schemas']['ProfileResponse'];
        };
      };
      /** Profile update payload invalid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProfileRequest'];
      };
    };
  };
  patchCurrentUser: {
    responses: {
      /** The updated profile profile */
      200: {
        content: {
          'application/json': components['schemas']['ProfileResponse'];
        };
      };
      /** Profile update payload invalid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PatchProfileRequest'];
      };
    };
  };
  getById_4: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Game was found */
      200: {
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Game was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  update_2: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Game was updated */
      200: {
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** Game could not be updated */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Game could not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Game could not be updated */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateGameRequest'];
      };
    };
  };
  deleteGame: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Game was deleted */
      200: unknown;
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Game could not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  createApiKey: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Api key was created */
      201: {
        content: {
          'application/json': components['schemas']['ApiKeyResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Game could not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Api-key not be created */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  revokeApiKey: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Api key was deleted */
      201: {
        content: {
          'application/json': components['schemas']['ApiKeyResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Game could not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getByGameId: {
    parameters: {
      query: {
        gameId: string;
        pageable: components['schemas']['Pageable'];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['PageTutorialProgressResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create: {
    responses: {
      /** The tutorial was saved successfully */
      201: {
        content: {
          'application/json': components['schemas']['TutorialProgressResponse'];
        };
      };
      /** Validation failed, e.g. gameId is empty */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** If a tutorial could not be created, a CONFLICT will be returned. */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTutorialRequest'];
      };
    };
  };
  search: {
    parameters: {
      query: {
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
        amount?: number;
        oldPrice?: number;
        bonus?: number;
        bannerUrl?: string;
        description?: string;
        title?: string;
        type?: string;
        tags?: string[];
        createdAt?: string;
        price?: number;
        id?: string;
        iconUrl?: string;
        properties?: { [key: string]: string };
        updatedAt?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['PagePurchasableResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_1: {
    responses: {
      /** Purchasable was created */
      201: {
        content: {
          'application/json': components['schemas']['PurchasableResponse'];
        };
      };
      /** Purchasable could not be created */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Purchasable could not be created */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreatePurchasableRequest'];
      };
    };
  };
  searchMatch: {
    responses: {
      /** Created ticket */
      201: {
        content: {
          'application/json': components['schemas']['TicketResponse'];
        };
      };
      /** Ticket search request data invalid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Users wallet balance is not enough */
      402: {
        content: {
          'application/json': components['schemas']['TicketResponse'];
        };
      };
      /** Could not add to ticket search */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchMatchRequest'];
      };
    };
  };
  cancelSearch: {
    responses: {
      /** Cancellation was successful */
      200: unknown;
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Ticket was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelSearchRequest'];
      };
    };
  };
  saveReplay: {
    parameters: {
      path: {
        matchId: string;
        playerToken: string;
      };
    };
    responses: {
      /** The replay was saved successfully */
      201: unknown;
      /** Validation failed, e.g. payload is empty */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** If a replay already exists for this match+player, the match was not found, the match is already finished (final score submitted or aborted) for the user or the player is not part of the match. */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SaveReplayRequest'];
      };
    };
  };
  updateScore: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Created */
      201: unknown;
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateScoreRequest'];
      };
    };
  };
  abortPlayer: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Player was aborted and can no longer play */
      202: {
        content: {
          'application/json': components['schemas']['MatchResponse'];
        };
      };
      /** Playertoken is valid but the match id is invalid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Match with player token was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Player has already a terminal match state */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AbortPlayerRequest'];
      };
    };
  };
  joinMatch: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['MatchResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JoinMatchRequest'];
      };
    };
  };
  search_2: {
    parameters: {
      query: {
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
        matchTiers?: string[];
        playersCount?: number;
        bannerUrl?: string;
        description?: string;
        gameUrl?: string;
        title?: string;
        ownerId?: string;
        tags?: string[];
        createdAt?: string;
        subtitle?: string;
        tutorialVideoUrl?: string;
        popularity?: number;
        genre?: string;
        id?: string;
        iconUrl?: string;
        updatedAt?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['PageGameResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_2: {
    responses: {
      /** Game was created */
      201: {
        content: {
          'application/json': components['schemas']['GameResponse'];
        };
      };
      /** Game could not be created */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Game could not be created */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateGameRequest'];
      };
    };
  };
  fastCheckout: {
    responses: {
      /** Checkout was successful */
      200: {
        content: {
          'application/json': components['schemas']['CheckoutResponse'];
        };
      };
      /** Basket could not be loaded */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Purchasable was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FastCheckoutRequest'];
      };
    };
  };
  addItemToBasket: {
    responses: {
      /** Item added to basket */
      200: {
        content: {
          'application/json': components['schemas']['BasketResponse'];
        };
      };
      /** Invalid request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Purchasable could not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Could not add item to basket */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddItemRequest'];
      };
    };
  };
  updateItemInBasket: {
    responses: {
      /** Item updated in basket */
      200: {
        content: {
          'application/json': components['schemas']['BasketResponse'];
        };
      };
      /** Invalid request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Purchasable could not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Could not update item in basket */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateItemRequest'];
      };
    };
  };
  register: {
    parameters: {
      header: {
        Authorization: string;
      };
    };
    responses: {
      /** The user was created */
      201: {
        content: {
          'application/json': components['schemas']['AuthToken'];
        };
      };
      /** User creation failed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Username or email already taken */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
  };
  refresh: {
    parameters: {
      header: {
        Authorization: string;
      };
    };
    responses: {
      /** The Refresh was successful */
      201: {
        content: {
          'application/json': components['schemas']['AuthToken'];
        };
      };
      /** Refresh failed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshExchangeRequest'];
      };
    };
  };
  login: {
    parameters: {
      header: {
        Authorization: string;
      };
    };
    responses: {
      /** The login was successful */
      201: {
        content: {
          'application/json': components['schemas']['AuthToken'];
        };
      };
      /** Login failed */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
  };
  changeUsername: {
    parameters: {
      header: {
        Authorization: string;
      };
    };
    responses: {
      /** The change of the username was successful */
      202: unknown;
      /** Missing required fields in request payload */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Username change failed */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeUsernameRequest'];
      };
    };
  };
  changePassword: {
    parameters: {
      header: {
        Authorization: string;
      };
    };
    responses: {
      /** The change of the password was successful */
      202: unknown;
      /** Missing required fields in request payload */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Password change failed */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
  };
  changeEmail: {
    parameters: {
      header: {
        Authorization: string;
      };
    };
    responses: {
      /** The change of the email was successful */
      202: unknown;
      /** Missing required fields in request payload */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Email change failed */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangeEmailRequest'];
      };
    };
  };
  getUserWallet: {
    responses: {
      /** The current user's wallet */
      200: {
        content: {
          'application/json': components['schemas']['WalletResponse'];
        };
      };
      /** UserId missing */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Could not get user's wallet */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getAggregatedUserWinRatio: {
    parameters: {
      path: {
        userId: string;
      };
      query: {
        period?: 'year' | 'month' | 'week' | 'day';
      };
    };
    responses: {
      /** The win-ratio stats for the user */
      200: {
        content: {
          'application/json': components['schemas']['WinRatioResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** User not found by id */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getById_2: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** The profile profile */
      200: {
        content: {
          'application/json': components['schemas']['ProfileResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Profile not found by id */
      404: {
        content: {
          'application/json': components['schemas']['ProfileResponse'];
        };
      };
    };
  };
  search_1: {
    parameters: {
      query: {
        /** If set then only notifications from the specified type will be returned */
        type?: string;
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['PageNotificationResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getTicketStatus: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Current ticket status */
      200: {
        content: {
          'application/json': components['schemas']['TicketResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Ticket was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  findReplay: {
    parameters: {
      path: {
        matchId: string;
        userId: string;
      };
    };
    responses: {
      /** The finished replay was found */
      200: {
        content: {
          'application/json': components['schemas']['FindReplayResponse'];
        };
      };
      /** When the match is not found or the playerToken is not part of the match. */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** When the replay can not be found even though the match is finished. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** When the player has not yet submitted a final score for the match where the replay should be stored for. */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getById_3: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Match with given id is found */
      200: {
        content: {
          'application/json': components['schemas']['MatchResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Match with given id can not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** Accepted */
      202: unknown;
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getPlayerInfo: {
    parameters: {
      path: {
        id: string;
        playerToken: string;
      };
    };
    responses: {
      /** Participant was found by playerToken in match */
      200: {
        content: {
          'application/json': components['schemas']['ParticipantResponse'];
        };
      };
      /** playerToken is valid but the match id is invalid */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Match with playerToken was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getByPlayerToken: {
    parameters: {
      path: {
        playerToken: string;
      };
    };
    responses: {
      /** Match with player token is found */
      200: {
        content: {
          'application/json': components['schemas']['MatchResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Match with player token can not be found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  searchHistory: {
    parameters: {
      query: {
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
        gameId?: string;
        timeoutAt?: string;
        fee?: number;
        scoreSnapshots?: string;
        denominationTier?: string;
        matchDifficulty?: 'beginner' | 'medium' | 'hard';
        finishedAt?: string;
        result?: string;
        createdAt?: string;
        availableReplays?: string;
        matchingState?: string;
        possibleWins?: string;
        entryCosts?: string;
        id?: string;
        matchId?: string;
        matchTier?: string;
        participants?: string;
        updatedAt?: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['PageMatchHistoryResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getHistoryById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['MatchHistoryResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** MatchHistory was not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getHistoryForUser: {
    parameters: {
      path: {
        userId: string;
      };
      query: {
        /** Zero-based page index (0..N) */
        page?: number;
        /** The size of the page to be returned */
        size?: number;
        /** Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['PageMatchHistoryResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getGameInfo: {
    responses: {
      /** OK */
      200: {
        content: {
          'application/json': components['schemas']['MatchTierResponse'][];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  getCurrentBasket: {
    responses: {
      /** Current user basket */
      200: {
        content: {
          'application/json': components['schemas']['BasketResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Basket could not be loaded */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteCurrentBasket: {
    responses: {
      /** Basket deleted */
      200: unknown;
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  deleteItemInBasket: {
    parameters: {
      path: {
        itemId: string;
      };
    };
    responses: {
      /** Item deleted from basket */
      200: {
        content: {
          'application/json': components['schemas']['BasketResponse'];
        };
      };
      /** Unauthorized */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** Could not delete item from basket */
      409: {
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
}

export interface external {}
